// Turns detector results into: a status-coloured dashboard, a REMEDIATION spec, and report.json.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const PRIO = {
  blocker: { label: "Launch blocker", rank: 0, emoji: "🔴" },
  "first-week": { label: "First week", rank: 1, emoji: "🟡" },
  nice: { label: "Nice to have", rank: 2, emoji: "🟢" },
  ongoing: { label: "Always-on", rank: 1, emoji: "🔵" },
};
const PHASE = { foundation: "Foundation", build: "Build", prelaunch: "Pre-launch", deploy: "Deploy", launch: "Launch day", postlaunch: "Post-launch" };

function applyProfileNA(check, res, profile, naMap) {
  const na = (evidence) => ({ status: "na", evidence });
  // capability-driven N/A: what the code review found does not apply
  if (naMap && naMap.has(check.id)) return na(naMap.get(check.id));
  const managed = profile.cloud && profile.cloud !== "aws" && profile.cloud !== "other";
  if (managed && ["S12", "O5", "DP5", "DP6", "DP10", "DP11"].includes(check.id)) return na(`Managed host (${profile.cloud}): the platform owns this`);
  if (profile.analytics === false && ["A7", "L3", "A2", "A4"].includes(check.id)) return na("No analytics/tracking in this project");
  return res;
}

export function assemble(meta, sections, checks, results, profile, naMap) {
  const augmented = checks.map((c) => {
    let r = results[c.id] || { status: "manual", evidence: "Verify this manually." };
    r = applyProfileNA(c, r, profile, naMap);
    return { ...c, status: r.status, evidence: r.evidence };
  });
  const applicable = augmented.filter((c) => c.status !== "na");
  const by = (s) => applicable.filter((c) => c.status === s);
  const summary = {
    total: checks.length,
    applicable: applicable.length,
    pass: by("pass").length,
    fail: by("fail").length,
    manual: by("manual").length,
    na: augmented.filter((c) => c.status === "na").length,
    autoChecked: by("pass").length + by("fail").length,
    // Score only what we could decide automatically. Manual "verify" items are a
    // separate to-do list, not failures, so they never drag the number down.
    readiness: (by("pass").length + by("fail").length) ? Math.round((by("pass").length / (by("pass").length + by("fail").length)) * 100) : 100,
    blockersFailing: applicable.filter((c) => c.priority === "blocker" && (c.status === "fail" || c.status === "manual")).length,
    blockersFailingHard: applicable.filter((c) => c.priority === "blocker" && c.status === "fail").length,
    blockersToVerify: applicable.filter((c) => c.priority === "blocker" && c.status === "manual").length,
    manualBlockers: applicable.filter((c) => c.status === "manual" && c.priority === "blocker").length,
    manualFirstWeek: applicable.filter((c) => c.status === "manual" && c.priority === "first-week").length,
    manualOngoing: applicable.filter((c) => c.status === "manual" && (c.priority === "nice" || c.priority === "ongoing")).length,
  };
  return { augmented, summary };
}

export function writeDashboard(root, templatePath, meta, sections, augmented, profile, summary) {
  const payload = JSON.stringify({
    meta: { ...meta, mode: "scan", profile, summary },
    sections,
    checks: augmented,
  });
  const tpl = readFileSync(templatePath, "utf8");
  const html = tpl.replace("__SHIP_KIT_DATA__", payload);
  const dir = join(root, "ship-kit-report");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "dashboard.html"), html);
  writeFileSync(join(dir, "report.json"), JSON.stringify({ generatedForProfile: profile, summary, checks: augmented.map((c) => ({ id: c.id, section: c.section, priority: c.priority, status: c.status, evidence: c.evidence })) }, null, 2) + "\n");
  return join(dir, "dashboard.html");
}

export function writeRemediation(root, meta, sections, augmented, profile, summary, dateStr) {
  const sName = (id) => (sections.find((s) => s.id === id) || {}).name || id;
  const fails = augmented.filter((c) => c.status === "fail")
    .sort((a, b) => PRIO[a.priority].rank - PRIO[b.priority].rank);
  const manuals = augmented.filter((c) => c.status === "manual")
    .sort((a, b) => PRIO[a.priority].rank - PRIO[b.priority].rank);

  let m = "";
  m += `# Ship Kit: what to fix before you launch\n\n`;
  m += `> **Reading this yourself?** Open **dashboard.html** (in this same \`ship-kit-report\` folder) in your browser instead. That is the friendly, colour-coded version. This file is a plain checklist for your AI assistant to work through.\n\n`;
  m += `Generated by Ship Kit on ${dateStr} for a project profile of: `;
  m += Object.entries(profile).filter(([k, v]) => v != null && v !== "" && !k.startsWith("_")).map(([k, v]) => `${k}=${v}`).join(", ") + `.\n\n`;
  m += `**${summary.fail} problem(s) to fix** and **${summary.manual} thing(s) to verify yourself**. `;
  m += `Of the ${summary.autoChecked} checks Ship Kit could decide automatically, ${summary.pass} pass and ${summary.fail} fail, so **${summary.readiness}%** of the automatic checks are green. The other ${summary.manual} need a human to confirm (they are a to-do list, not failures, and do not count against the score), and ${summary.na} do not apply to this project.\n\n`;
  if (summary.blockersFailingHard > 0) m += `> ${summary.blockersFailingHard} launch-blocker(s) are failing and must be fixed before launch.\n\n`;
  else if (summary.blockersToVerify > 0) m += `> No launch-blockers are failing automatically, but ${summary.blockersToVerify} still need you to verify them by hand (see section 2).\n\n`;
  else m += `> No launch-blockers failing. Work the first-week items next.\n\n`;

  m += `## How to use this file\n\n`;
  m += `Two kinds of item. **Problems to fix** (section 1) are things Ship Kit is sure are missing or broken. **Things to verify** (sections 2 to 4) are things a code scan cannot judge on its own, so they are unconfirmed, not necessarily wrong. A coding agent can resolve most of the "verify" items by reading the code and the live site; only a few genuinely need a human.\n\n`;
  m += `> Instruction for the agent: Help me get this project launch-ready. (1) Fix the problems in section 1, following the "How to fix" guidance. Some fixes are a hosting or infrastructure change (a CDN setting, a DNS record, a cloud console setting), not a file in this repo, so check whether you have the access a fix needs before starting it, and say so plainly if you do not. (2) Then investigate the "Verify before launch" items in section 2: check each one yourself by reading the code (and the live site if a URL is set), and report back grouped as: already fine, actually a problem (fix these), or needs the human (like walking the flow on a phone, or a business or legal call). Treat every "What we found" line as ground truth. Do not weaken tests or fake a pass. Ask before any irreversible action (deploys, deletions, sends). When you report back, write plainly: short sentences, no em dashes. When done, re-run \`node cli.mjs scan --yes\` to refresh this file.\n\n`;

  m += `## 1. Fix these (detected problems)\n\n`;
  if (!fails.length) m += `_Nothing failed the automated scan._\n\n`;
  let i = 1;
  for (const c of fails) {
    m += `### ${i++}. \`${c.id}\` ${c.title}\n\n`;
    m += `${PRIO[c.priority].emoji} **${PRIO[c.priority].label}** · ${sName(c.section)} · Phase: ${PHASE[c.phase]}\n\n`;
    m += `- **What we found:** ${c.evidence}\n`;
    m += `- **How to fix:** ${c.how}\n`;
    m += `- **Why it matters:** ${c.why}\n`;
    if (c.prompt) m += `\n\`\`\`text\n${c.prompt}\n\`\`\`\n`;
    m += `\n`;
  }

  const vBlock = manuals.filter((c) => c.priority === "blocker");
  const vWeek = manuals.filter((c) => c.priority === "first-week");
  const vLater = manuals.filter((c) => c.priority === "nice" || c.priority === "ongoing");
  m += `## 2. Verify before launch (${vBlock.length})\n\n`;
  m += `A quick code scan cannot decide these on its own, so they are unconfirmed (not necessarily wrong). Your AI can check most of them for you by reading the code and the live site; only a few genuinely need you (like walking the core flow on your phone).\n\n`;
  if (!vBlock.length) m += `_Nothing critical left to verify by hand._\n\n`;
  else { for (const c of vBlock) m += `- \`${c.id}\` **${c.title}**: ${c.evidence}\n`; m += `\n`; }

  if (vWeek.length) {
    m += `## 3. Verify in the first week (${vWeek.length})\n\n`;
    m += vWeek.map((c) => `\`${c.id}\` ${c.title}`).join(" · ") + "\n\n";
  }
  if (vLater.length) {
    m += `## 4. Ongoing best-practices (${vLater.length}, skim when you have time)\n\n`;
    m += vLater.map((c) => `\`${c.id}\` ${c.title}`).join(" · ") + "\n\n";
  }

  m += `## 5. Passing (${summary.pass})\n\n`;
  const pass = augmented.filter((c) => c.status === "pass");
  m += pass.length ? pass.map((c) => `\`${c.id}\` ${c.title}`).join(" · ") + "\n" : `_Nothing passed yet._\n`;

  // Not applicable, grouped by reason (transparent, but out of the way)
  const naItems = augmented.filter((c) => c.status === "na");
  if (naItems.length) {
    const byReason = new Map();
    for (const c of naItems) { const r = c.evidence || "Not applicable"; if (!byReason.has(r)) byReason.set(r, []); byReason.get(r).push(c.id); }
    m += `\n## Not checked (${naItems.length} skipped, and why)\n\n`;
    m += `Ship Kit reviewed the code and skipped these because they do not apply to this project:\n\n`;
    for (const [reason, ids] of [...byReason.entries()].sort((a, b) => b[1].length - a[1].length)) {
      m += `- **${reason}** (${ids.length}): ${ids.join(", ")}\n`;
    }
    m += `\nIf any of these are wrong (for example the scan missed your database), re-run with an explicit flag, e.g. \`--db postgres\`.\n`;
  }
  m += `\n<sub>Ship Kit scan. Re-run to regenerate. Statuses: fail = detected problem, manual = verify yourself, na = not applicable (auto-detected from the code).</sub>\n`;

  const dir = join(root, "ship-kit-report");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "REMEDIATION.md"), m);
  return join(dir, "REMEDIATION.md");
}
